# Generated by Django 4.2.25 on 2025-11-06 08:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBehavior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_id', models.CharField(max_length=10)),
                ('scroll_velocity', models.FloatField()),
                ('hover_duration', models.CharField(max_length=10)),
                ('click_error_rate', models.FloatField()),
                ('focus_mode', models.CharField(max_length=10)),
                ('action', models.CharField(choices=[('Normal', 'Normal'), ('Normal Layout', 'Normal Layout'), ('Slow Scroll Detected', 'Slow Scroll Detected'), ('Hovering over classes', 'Hovering over classes'), ('Focus View', 'Focus View'), ('Click Error Mode', 'Click Error Mode'), ('UI Dimmed', 'UI Dimmed'), ('UI Restored (User Idle)', 'UI Restored (User Idle)'), ('Enlarge Mode', 'Enlarge Mode'), ('Account Created', 'Account Created')], max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behaviors', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
