# Generated by Django 4.2.25 on 2025-11-19 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbehavior',
            name='action',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Normal Layout', 'Normal Layout'), ('Slow Scroll Detected', 'Slow Scroll Detected'), ('Fast Scroll Detected', 'Fast Scroll Detected'), ('Hovering over classes', 'Hovering over classes'), ('Focus View', 'Focus View'), ('Click Error Mode', 'Click Error Mode'), ('UI Dimmed', 'UI Dimmed'), ('UI Restored (User Idle)', 'UI Restored (User Idle)'), ('Enlarge Mode', 'Enlarge Mode'), ('Account Created', 'Account Created')], max_length=50),
        ),
    ]
